services: 
  frontend:
    build: ./frontend
    ports: ['3001:80']
    secrets: 
      - frontend_secret
    # networks: 
      #  - frontend-backend-net

  backend:
    build: 
      context: ./backend
      target: builder
    ports: ['3002:8000']
    secrets: 
      - backend_secret
    # networks:
    #  - backend-db-net
      # - frontend-backend-net
    # expose:
    #   - 8000

  mongodb:
    image: mongo:7.0
    volumes:
      - mongodb:/data/db
    # networks:
    #  - backend-db-net
    # expose: 
    #   - 27017

  proxy: 
    build: ./proxy
    ports: ['3000:80']

# networks:
#   frontend-backend-net: 
#   backend-db-net:

secrets: 
  frontend_secret: 
    file: ./frontend/.env
  backend_secret:
    file: ./backend/.env

volumes:
  mongodb: