export { default as FilesPage } from './files/FilesPage';
export { default as FilePage } from './files/FilePage';
export { default as StatsPage } from './StatsPage';
export { default as UploadFilesPage } from './files/UploadFilesPage';
export { default as Base } from './Base';
export { default as SignInPage } from './auth/SignInPage';
export { default as SignUpPage } from './auth/SignUpPage';
export { default as SettingsAppearancePage } from './settings/SettingsAppearancePage';
export { default as NotFoundPage } from './errors/NotFoundPage';